apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-app
  labels:
    app: gateway-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service-app
  template:
    metadata:
      labels:
        app: gateway-service-app
    spec:
      containers:
        - name: gateway-service-app
          image: thimmegowdatp/gateway-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service-svc
spec:
  type: LoadBalancer
  selector:
    app: gateway-service-app

  ports:
  - port: 80
    targetPort: 9090