apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-1-app
  labels:
    app: service-1-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-1-app
  template:
    metadata:
      labels:
        app: service-1-app
    spec:
      containers:
        - name: service-1-app
          image: thimmegowdatp/service-1:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: service-1-svc
spec:
  type: ClusterIP
  selector:
    app: service-1-app

  ports:
  - port: 80
    targetPort: 8001



