apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-2-app
  labels:
    app: service-2-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-2-app
  template:
    metadata:
      labels:
        app: service-2-app
    spec:
      containers:
        - name: service-2-app
          image: thimmegowdatp/service-2:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: service-2-svc
spec:
  type: ClusterIP
  selector:
    app: service-2-app

  ports:
  - port: 80
    targetPort: 8002